# How to create an empty and full Numpy array?

Empty

In [6]:
import numpy as np
a=np.empty((0,0))
print(a)

[]


Full

In [13]:
a=np.full([5,4],67,dtype=int)
print(a)

[[67 67 67 67]
 [67 67 67 67]
 [67 67 67 67]
 [67 67 67 67]
 [67 67 67 67]]


# Create a numpy_array_filled with all zeros.

In [2]:
import numpy as np
np.zeros((5,5),np.uint8)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=uint8)

# Create a numpy array filled with all ones.

In [3]:
np.ones((5,5),np.uint8)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=uint8)

# Cheack whether a numpy array contains a specified row.

In [14]:
a=np.array([[5,6],[7,8]])
a.tolist()


[[5, 6], [7, 8]]

In [15]:
[5,6] in a.tolist()

True

# How to remove rows in numpy.Arrays that contain non numeric values

In [80]:
a = np.array([[10.5, 22.5, 3.8],[23.45, 50, 78.7],[41, np.nan, np.nan]])
print(a)
print(a[~np.isnan(a).any(axis=1)])

[[10.5  22.5   3.8 ]
 [23.45 50.   78.7 ]
 [41.     nan   nan]]
[10.5  22.5   3.8  23.45 50.   78.7  41.  ]


# Remove single dimensional entries from the shape of an array

In [42]:
a=np.array([[5,6,7,8]])
print(a.shape)
print(a)
b=np.squeeze(a)
print(b)
print(b.shape)

(1, 4)
[[5 6 7 8]]
[5 6 7 8]
(4,)


# Find the number of occurences of a sequence in a numpy array.

In [84]:
a = np.array([[2, 8, 9, 4],[9, 4, 9, 4],[4, 5, 9, 7],[2, 9, 4, 3]])
output = repr(a).count("9, 4")
print(output)


4


# Find the most frequent value in numpy array.

In [53]:
x = np.random.randint(0, 10, 40)
print("Original array:")
print(x)
print("Most frequent value in the above array:")
print(np.bincount(x))
print(np.bincount(x).argmax())

Original array:
[6 2 5 6 0 6 5 6 2 1 5 6 1 3 6 6 3 3 9 7 4 6 1 8 7 4 1 7 6 5 8 7 3 6 0 7 7
 3 5 7]
Most frequent value in the above array:
[ 2  4  2  5  2  5 10  7  2  1]
6


# Combining a one and two dimensional numpy array

In [57]:
num_1d = np.arange(5)
print("One dimensional array:")
print(num_1d)

num_2d = np.arange(10).reshape(2,5)
print("\nTwo dimensional array:")
print(num_2d)

# Combine 1-D and 2-D arrays and display
# their elements using numpy.nditer()
for a, b in np.nditer([num_1d, num_2d]):
	print('%d:%d'%(a, b),)


One dimensional array:
[0 1 2 3 4]

Two dimensional array:
[[0 1 2 3 4]
 [5 6 7 8 9]]
0:0
1:1
2:2
3:3
4:4
0:5
1:6
2:7
3:8
4:9


# How to build an array of all combinations of two numpy arrays

In [59]:
np.stack(np.meshgrid([1, 2, 3], [4, 5], [6, 7]), -1).reshape(-1, 3)


array([[1, 4, 6],
       [1, 4, 7],
       [2, 4, 6],
       [2, 4, 7],
       [3, 4, 6],
       [3, 4, 7],
       [1, 5, 6],
       [1, 5, 7],
       [2, 5, 6],
       [2, 5, 7],
       [3, 5, 6],
       [3, 5, 7]])

In [65]:
# importing Numpy package
import numpy as np

# creating 2 numpy arrays
array_1 = np.array([1, 2])
array_2 = np.array([4, 6])

print("Array-1")
print(array_1)

print("\nArray-2")
print(array_2)

# combination of elements of array_1 and array_2
# using numpy.meshgrid().T.reshape()
comb_array = np.array(np.meshgrid(array_1, array_2)).reshape(-1, 2)

print("\nCombine array:")
print(comb_array)


Array-1
[1 2]

Array-2
[4 6]

Combine array:
[[1 2]
 [1 2]
 [4 4]
 [6 6]]


# How to add border around a numpy array.

In [70]:
array = np.ones((2, 2))

print("Original array")
print(array)

print("\n0 on the border and 1 inside the array")

# constructing border of 0 around 2D identity matrix
# using np.pad()
array = np.pad(array, pad_width=1, mode='constant',constant_values=0)

print(array)


Original array
[[1. 1.]
 [1. 1.]]

0 on the border and 1 inside the array
[[0. 0. 0. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 0. 0. 0.]]


# How to compare two numpy arrays.

In [74]:
import numpy as np

an_array = np.array([[1, 2], [3, 4]])
another_array = np.array([[1, 2], [3, 4]])

comparison = an_array == another_array
equal_arrays = comparison.all()
print(comparison)
print(equal_arrays)


[[ True  True]
 [ True  True]]
True


# How to check whether specified values are present in numpy array?

In [75]:
n_array = np.array([[2, 3, 0],[4, 1, 6]])

print("Given array:")
print(n_array)

# Checking whether specific values
# are present in "n_array" or not
print(2 in n_array)
print(0 in n_array)
print(6 in n_array)
print(50 in n_array)
print(10 in n_array)


Given array:
[[2 3 0]
 [4 1 6]]
True
True
True
False
False


# How to get all 2d diagonals of a 3d numpy array? 

In [85]:
# Import the numpy package
import numpy as np

# Create 3D-numpy array
# of 4 rows and 4 columns
arr = np.arange(3 * 4 * 4).reshape(3, 4, 4)

print("Original 3d array:\n",arr)

# Create 2D diagonal array
diag_arr = np.diagonal(arr,axis1 = 1,axis2 = 2) #axis1: represents first axis to be taken for 2-d subarray 
#axis2: represents second axis to be taken for 2-d subarray 


print("2d diagonal array:\n",diag_arr)


Original 3d array:
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]

 [[32 33 34 35]
  [36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]]
2d diagonal array:
 [[ 0  5 10 15]
 [16 21 26 31]
 [32 37 42 47]]


# Flatten a 2d numpy array into 1d array

In [77]:
import numpy as np
# Create a 2D numpy array from list of lists
arr = np.array([[7, 4, 2],
                [5, 3, 6],
                [2, 9, 5]])
# get a flatten 1D copy of 2D Numpy array
flat_array = arr.flatten()
print('1D Numpy Array:')
print(flat_array)

1D Numpy Array:
[7 4 2 5 3 6 2 9 5]


# Change data type of given numpy.

In [78]:
array = np.array([1.5, 2.6, 3.7, 4.8, 5.9])
array = array.astype(np.int32)
print(array)

[1 2 3 4 5]


# Reverse a numpy array

In [79]:
a = np.array([1, 2, 3, 6, 4, 5])

# using shortcut method to reverse
res = np.flip(a)

# printing result
print("final array", str(res))


final array [5 4 6 3 2 1]
